//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int CalibrationID { get; set; }
        public int CalibrationTypeID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime CalibrationDate { get; set; }
        public string Description { get; set; }
    
        public virtual CalibrationType CalibrationType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
