//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceValue
    {
        public int ReferenceValueID { get; set; }
        public int CalibrationTypeID { get; set; }
        public int DeviceTypeID { get; set; }
        public string ValueName { get; set; }
        public string Value { get; set; }
    
        public virtual CalibrationType CalibrationType { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
