//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringSystem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestResultID { get; set; }
        public int TestID { get; set; }
        public string MeasuredValue { get; set; }
        public string Deviation { get; set; }
        public string Description { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
